### ISSUE TITLE
Uncaught SyntaxError: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed. 

### ISSUE THREAD

**Issue by madprops** [moccu/django-omnibus#13]
I'm following the documentation and when I'm trying to create a connection I get this error.

Running Django 1.6
omnibus added to  installed apps
template_context_processors added
template tags included
omnibusd started

**Comment by bkl1989** [comment]
It would be helpful to know what you were doing wrong. Do you remember what it was?

**Comment by madprops** [comment]
Sorry, I should have stated what it was back then. I have no idea now.
